[package]
name = "pg-schema-diff"
version = "0.0.1"
authors = ["Eric B. Ridge <eebbrr@gmail.com>"]
edition = "2021"
license = "LICENSE"

[dependencies]
colored = "2.0.0"
indexmap = "2.5.0"
postgres-parser = "*"
rand = "0.8.3"
